return {
    "stevearc/conform.nvim",
    lazy = true,
    opts = {
        formatters_by_ft = {
            javascript = { "biome", "biome-check" },
            typescript = { "biome", "biome-check" },
            typescriptreact = { "biome", "biome-check" },
            json = { "biome", "biome-check" },
            yaml = { "prettierd" },
            html = { "prettierd" },
            css = { "biome" },
            scss = { "biome" },
            markdown = { "prettierd" },
            lua = { "stylua" },
            java = { "google-java-format" },
            cpp = { { "clang-format", "astyle" } },
            c = { { "clang-format", "astyle" } },
            rust = { { "rustfmt", "rustfmt-nightly" } },
            python = { "black" },
            go = { "goimports", "gofmt" },
            templ = { "templ" },
            cs = { "csharpier" },
        },
    },
}
